package by.hustlestar.controller;

/**
 * Created by Hustler on 30.10.2016.
 */
enum CommandName {
    LOGIN, REGISTER, LOG_OUT, MY_PROFILE,
    ALL_MOVIES, MOVIE_BY_ID, FIND_MOVIE_BY_TITLE,
    ADD_MOVIE, UPDATE_MOVIE,
    BAN_USER, UNBAN_USER, DELETE_REVIEW,
    MOVIES_BY_COUNTRY, MOVIES_BY_GENRE,
    MOVIES_OF_TEN_YEAR_PERIOD, MOVIES_OF_YEAR,
    ADD_REVIEW, LIKE_REVIEW,
    ADD_RATING,
    VIEW_ALL_USERS, VIEW_USER, VIEW_ALL_BANNED_USERS,
    CHANGE_LANGUAGE,
}
